#!/usr/bin/env python3
"""
sync_agent_rules.py

Single source of truth:
  .agent/principles.yaml  (JSON-in-YAML format)

Generated targets:
  .codex/rules.md
  .gemini/context.md
  .trae/instruction.md
  .cursorrules

Usage:
  python tools/sync_agent_rules.py
  python tools/sync_agent_rules.py --check
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / ".agent" / "principles.yaml"
AUTO_NOTE = "<!-- AUTO-GENERATED by tools/sync_agent_rules.py from .agent/principles.yaml -->"


def _load_source(path: Path) -> Dict:
    # principles.yaml is stored as JSON text, which is valid YAML 1.2.
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _render_codex(src: Dict) -> str:
    g = src["global"]
    c = src["codex"]
    lines: List[str] = [
        AUTO_NOTE,
        f"# {c['title']}",
        "",
        f"Source version: `{src['meta']['version']}`",
        "",
    ]
    for i, rule in enumerate(c["rules"], start=1):
        lines.append(f"{i}. **Rule {i}**: {rule}")
    lines.extend(
        [
            "",
            "Style:",
            f"- {', '.join(c['style'])}",
            "",
            "Core Paths:",
            f"- Active: `{g['core_paths']['primary_math_core']}` / `{g['core_paths']['primary_kernel']}`",
            f"- Legacy: `{g['core_paths']['legacy_math_core']}` / `{g['core_paths']['legacy_kernel']}`",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _render_gemini(src: Dict) -> str:
    g = src["global"]
    c = src["gemini"]
    lines: List[str] = [
        AUTO_NOTE,
        f"# {c['title']}",
        "",
        c["identity"],
        f"Your Core Logic is defined in `{g['constitution_path']}`.",
        f"Your Skills are in `{g['skills_root']}/`.",
        "",
        "**CRITICAL INSTRUCTION**:",
    ]
    for item in c["critical_instruction"]:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_trae(src: Dict) -> str:
    c = src["trae"]
    ctx = c["context"]
    lines: List[str] = [
        AUTO_NOTE,
        f"# {c['title']}",
        "",
        "> **ATTENTION AGENT**: You are operating within the OMEGA Antigravity Environment.",
        "",
        "## Prime Directives",
    ]
    for i, directive in enumerate(c["prime_directives"], start=1):
        lines.append(f"{i}. **Directive {i}**: {directive}")
    lines.extend(
        [
            "",
            "## Context",
            f"- **Root**: `{ctx['root']}`",
            f"- **Environment**: `{ctx['environment']}`",
            "- **Key Files**:",
        ]
    )
    for fp in ctx["key_files"]:
        lines.append(f"  - `{fp}`")
    lines.append(f"- **Legacy Note**: {ctx['legacy_note']}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_cursor(src: Dict) -> str:
    c = src["cursor"]
    lines: List[str] = [
        "# Cursor Rules for OMEGA",
        "",
    ]
    for inc in c["includes"]:
        lines.append(f"@{inc}")
    lines.append("")
    for i, rule in enumerate(c["rules"], start=1):
        lines.append(f"{i}. {rule}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _targets(src: Dict) -> Dict[Path, str]:
    return {
        ROOT / ".codex" / "rules.md": _render_codex(src),
        ROOT / ".gemini" / "context.md": _render_gemini(src),
        ROOT / ".trae" / "instruction.md": _render_trae(src),
        ROOT / ".cursorrules": _render_cursor(src),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=str(DEFAULT_SOURCE))
    ap.add_argument("--check", action="store_true", help="Only check drift; do not write.")
    args = ap.parse_args()

    source = Path(args.source).resolve()
    src = _load_source(source)
    planned = _targets(src)

    drift: List[Path] = []
    for path, expected in planned.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            drift.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                with path.open("w", encoding="utf-8", newline="\n") as f:
                    f.write(expected)

    if args.check:
        if drift:
            print("DRIFT DETECTED:")
            for p in drift:
                print(f"- {p.relative_to(ROOT)}")
            return 1
        print("No drift.")
        return 0

    if drift:
        print("Updated:")
        for p in drift:
            print(f"- {p.relative_to(ROOT)}")
    else:
        print("No changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
